<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>fnb_pos_inventory_system</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Admin\Data\**" />
    <Compile Remove="Areas\Admin\Models\**" />
    <Compile Remove="Areas\Admin\Views\**" />
    <Compile Remove="Areas\Auth\Data\**" />
    <Compile Remove="Areas\Auth\Models\**" />
    <Compile Remove="Areas\Auth\Views\**" />
    <Compile Remove="Areas\Cashier\**" />
    <Compile Remove="Areas\Inventory\Data\**" />
    <Compile Remove="Areas\Inventory\Models\**" />
    <Compile Remove="Areas\Inventory\Views\**" />
    <Compile Remove="Controllers\**" />
    <Content Remove="Areas\Admin\Data\**" />
    <Content Remove="Areas\Admin\Models\**" />
    <Content Remove="Areas\Admin\Views\**" />
    <Content Remove="Areas\Auth\Data\**" />
    <Content Remove="Areas\Auth\Models\**" />
    <Content Remove="Areas\Auth\Views\**" />
    <Content Remove="Areas\Cashier\**" />
    <Content Remove="Areas\Inventory\Data\**" />
    <Content Remove="Areas\Inventory\Models\**" />
    <Content Remove="Areas\Inventory\Views\**" />
    <Content Remove="Controllers\**" />
    <EmbeddedResource Remove="Areas\Admin\Data\**" />
    <EmbeddedResource Remove="Areas\Admin\Models\**" />
    <EmbeddedResource Remove="Areas\Admin\Views\**" />
    <EmbeddedResource Remove="Areas\Auth\Data\**" />
    <EmbeddedResource Remove="Areas\Auth\Models\**" />
    <EmbeddedResource Remove="Areas\Auth\Views\**" />
    <EmbeddedResource Remove="Areas\Cashier\**" />
    <EmbeddedResource Remove="Areas\Inventory\Data\**" />
    <EmbeddedResource Remove="Areas\Inventory\Models\**" />
    <EmbeddedResource Remove="Areas\Inventory\Views\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <None Remove="Areas\Admin\Data\**" />
    <None Remove="Areas\Admin\Models\**" />
    <None Remove="Areas\Admin\Views\**" />
    <None Remove="Areas\Auth\Data\**" />
    <None Remove="Areas\Auth\Models\**" />
    <None Remove="Areas\Auth\Views\**" />
    <None Remove="Areas\Cashier\**" />
    <None Remove="Areas\Inventory\Data\**" />
    <None Remove="Areas\Inventory\Models\**" />
    <None Remove="Areas\Inventory\Views\**" />
    <None Remove="Controllers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Customer\Controllers\" />
    <Folder Include="Areas\Customer\Data\" />
    <Folder Include="Areas\Customer\Models\" />
    <Folder Include="Areas\Customer\Views\" />
    <Folder Include="Areas\Inventory\Controllers\" />
    <Folder Include="Areas\Kitchen\Controllers\" />
    <Folder Include="Areas\Kitchen\Data\" />
    <Folder Include="Areas\Kitchen\Models\" />
    <Folder Include="Areas\Kitchen\Views\" />
    <Folder Include="Areas\Profile\Controllers\" />
    <Folder Include="Areas\Profile\Data\" />
    <Folder Include="Areas\Profile\Models\" />
    <Folder Include="Areas\Profile\Views\" />
  </ItemGroup>

</Project>
